package com.A14_Exception;

public class E01ArithmeticExceptionWithoutExceptionHandling 
{
	public static void main(String[] args) 
	{
		int num1=50;
		int num2=0;
		int div;
		
		div=num1/num2;
		
		System.out.println("num1= "+num1);
		System.out.println("num2= "+num2);
		System.out.println("division of two number is div "+div);
		
		
	}
}
